version: '3.8'
services:
  todolist:
    build: .   # Indique le répertoire contenant le Dockerfile
    ports:
      - "8081:8080"   # Redirige le port 8080 du conteneur vers le port 8081 de la machine hôte


