spring:
  sql:
    init:
      mode: always # Permet l'exécution automatique de schema.sql au démarrage
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres # Hostname 'postgres' correspondant au service Docker
    username: postgres
    password: example
